Repository Pororii/PoSSG, pull requests merged in 2024-08, with the labels that each got.

#8 [Feat 💡] 타입 정의
  frontend/src/interfaces/Interfaces.ts
Labels: Feat

#9 Feature/#2/api setting
  frontend/.gitignore
  frontend/src/api/axiosInstance.ts
  frontend/src/api/portfolio/getAskRecommend.tsx
  frontend/src/api/portfolio/getMakePortfolio.tsx
  frontend/src/api/portfolio/getPortfolio.tsx
  frontend/src/api/portfolio/getPortfolioFile.tsx
  frontend/src/api/portfolio/getRecommend.tsx
  frontend/src/api/portfolio/postEditPortfolio.tsx
  frontend/src/api/project/getMyFolder.tsx
  frontend/src/api/project/postDeleteFile.tsx
  frontend/src/api/project/postFolderSummary.tsx
  frontend/src/api/project/postMyProjectFiles.tsx
  frontend/src/api/project/postProjectFiles.tsx
  frontend/src/api/user/getUser.tsx
  frontend/src/api/user/getUsers.tsx
  frontend/src/api/user/postCheckEmail.tsx
  frontend/src/api/user/postEditInfo.tsx
  frontend/src/api/user/postLogin.tsx
  frontend/src/api/user/postRegister.tsx
Labels: Feat, Test

#11 [Feat 💡] 로그인 기능
  frontend/public/img/Herosection_possg.png
  frontend/public/img/charactor.png
  frontend/public/img/logo.png
  frontend/public/img/logo_b.png
  frontend/public/img/logo_black.png
  frontend/public/img/rocket-3d-icon3.png
  frontend/public/img/thumbnails_green.png
  frontend/public/img/thumbnails_pink.png
  frontend/public/img/thumbnails_purple.png
  frontend/public/img/thumbnails_skyblue.png
  frontend/src/api/portfolio/getAskRecommend.tsx
  frontend/src/api/portfolio/getMakePortfolio.tsx
  frontend/src/api/portfolio/getPortfolio.tsx
  frontend/src/api/portfolio/getPortfolioFile.tsx
  frontend/src/api/portfolio/getRecommend.tsx
  frontend/src/api/portfolio/postEditPortfolio.tsx
  frontend/src/api/project/getMyFolder.tsx
  frontend/src/api/project/postDeleteFile.tsx
  frontend/src/api/project/postFolderSummary.tsx
  frontend/src/api/project/postMyProjectFiles.tsx
  frontend/src/api/project/postProjectFiles.tsx
  frontend/src/api/user/getUser.tsx
  frontend/src/api/user/getUsers.tsx
  frontend/src/api/user/postCheckEmail.tsx
  frontend/src/api/user/postEditInfo.tsx
  frontend/src/api/user/postLogin.tsx
  frontend/src/api/user/postRegister.tsx
  frontend/src/components/NotFoundPage/NotFound.tsx
  frontend/src/pages/LoginPage/Login.tsx
  frontend/src/router.tsx
Labels: Feat, Design

#12 [Feat 💡] 회원가입 기능
  frontend/src/pages/RegisterPage/Register.tsx
  frontend/src/router.tsx
Labels: Feat, Design

#13 [Feat 💡] Navbar 컴포넌트
  frontend/src/App.tsx
  frontend/src/components/NotFoundPage/Navbars/Navbars.tsx
  frontend/src/stores/useUserStore.ts
  frontend/src/utils/localStorage.ts
Labels: Feat, Design

#15 [Feat 💡] 홈(프로젝트) 페이지
  frontend/src/App.tsx
  frontend/src/api/project/postManageFolder.tsx
  frontend/src/api/project/postUploadThumbnail.tsx
  frontend/src/components/HeroSection/HeroSection.tsx
  frontend/src/components/Navbars/Navbars.tsx
  frontend/src/pages/HomePage/Home.tsx
  frontend/src/pages/HomePage/components/InputForm.tsx
  frontend/src/pages/HomePage/components/ProjectFolder.tsx
  frontend/src/stores/useFolderStore.ts
Labels: Feat, Design

#17 [Feat 💡] 프로젝트 디테일 페이지 기능
  frontend/src/pages/HomePage/components/ProjectFolder.tsx
  frontend/src/pages/ProjectDetailPage/ProjectDetail.tsx
  frontend/src/pages/ProjectDetailPage/components/ProjectFile.tsx
  frontend/src/pages/ProjectDetailPage/components/ProjectPreview.tsx
  frontend/src/router.tsx
  frontend/src/stores/useFolderStore.ts
Labels: Feat, Design

#19 [Feat 💡] 포트폴리오 페이지 기능
  frontend/src/api/portfolio/getPortfolio.tsx
  frontend/src/components/Footer/Footer.tsx
  frontend/src/components/Loading/Loading.tsx
  frontend/src/interfaces/Interfaces.ts
  frontend/src/pages/PortfolioPage/Portfolio.tsx
  frontend/src/pages/PortfolioPage/components/PortfolioSection.tsx
  frontend/src/pages/PortfolioPage/components/Recommend.tsx
  frontend/src/router.tsx
  frontend/src/stores/usePortfolioStore.ts
Labels: Feat, Design

#23 [Test 💻] 조건문 오류 수정
  frontend/src/pages/PortfolioPage/components/Recommend.tsx
Labels: Test

#24 [Feat💡] MyInfo 모달 생성 + 연결
  frontend/package-lock.json
  frontend/package.json
  frontend/src/api/user/getUser.tsx
  frontend/src/api/user/postEditInfo.tsx
  frontend/src/components/MyInfo/MyInfoCard.tsx
  frontend/src/components/Navbars/Navbars.tsx
  frontend/src/index.tsx
Labels: Feat

#26 [Fix ✏️] 파일 삭제 수정 및 삭제 모달 연결
  frontend/src/pages/HomePage/components/ProjectFolder.tsx
  frontend/src/pages/ProjectDetailPage/ProjectDetail.tsx
  frontend/src/pages/ProjectDetailPage/components/ProjectFile.tsx
Labels: fix, Design

#30 [Feat 💡] 파일 다운로드 기능
  frontend/src/pages/PortfolioPage/components/PortfolioSection.tsx
Labels: Feat

#33 Fix/#21/portfolio fix
  frontend/src/pages/PortfolioPage/components/PortfolioSection.tsx
Labels: fix

#35 [Design 🎨] 상단 홈페이지 바 수정
  frontend/public/index.html
Labels: Design

#36 Fix/#22/recommend
  frontend/src/pages/PortfolioPage/components/PortfolioSection.tsx
  frontend/src/pages/PortfolioPage/components/Recommend.tsx
Labels: fix, Design
